%YAML:1.0

# Camera calibration and distortion parameters (OpenCV) 
Camera.fx: 458.654
Camera.fy: 457.296
Camera.cx: 367.215
Camera.cy: 248.375

Camera.k1: -0.28340811
Camera.k2: 0.07395907
Camera.p1: 0.00019359
Camera.p2: 1.76187114e-05

# Camera resolution
Camera.width: 752
Camera.height: 480

Camera.fps: 20

feature_num: 300
pyramid_num: 8
level_factor: 1.2
FAST_th_init: 20
FAST_th_min: 7